services:

  db:
    image: postgres:16
    container_name: profile-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build: .
    container_name: profile-api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/profile
    ports:
      - "3000:3000"


volumes:
  postgres_data: